version: '3.8'
services:
  uidev:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: user-interface
    stdin_open: true
    volumes:
      - ./:/app
